# Site settings
title: Tomoharu Kawata
description: 'Business Card Page'
url: 'https://toxumuharu.github.io/'
baseurl: ''
profilepic: '/images/tokawata.jpg'
bkimage: '/images/bk1.jpg'
# google_analytics: UA-XXXXXX-X
font_awesome: 'ab4d10fbaa.js'

author:
  name: 'Tomoharu Kawata'
  # email: thomas@zuehlke.cloud
  # mastodon: tzuehlke@mstdn.social
  # twitter_username: thomzuehlke
  # facebook_username: joshgerdes
  github_username:  toxumuharu
  linkedin_username:  tomoharu-kawata-44670b15b
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
